# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\Usuario:
            algorithm: bcrypt
            cost: 4
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~

    # http://symfony.com/doc/current/book/security.html#hierarchical-roles
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        usuarios:
            entity: { class: AppBundle\Entity\Usuario, property: num_identi }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # the login page has to be accessible for everybody
        entrada:
            pattern:  ^/entrar$
            security: false

        registro:
            pattern:  ^/registro
            security: false

        registro-pers:
            pattern:  ^/registro/datos-personales
            security: false

        registro-formac:
            pattern:  ^/registro/formacion
            security: false

        ayuda:
            pattern:  ^/ayuda
            security: false


        # secures part of the application
        area_protegida:
            pattern:    ^/
            # it's important to notice that in this case _demo_security_check and _demo_login
            # are route names and that they are specified in the AcmeDemoBundle

            form_login:
                login_path: entrar
                check_path: comprobar

            logout:
                path: salir
                target: entrar

            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"


            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
